import { defineConfig } from 'cspell'

export default defineConfig({
  words: [
    'azat',
    'browserslistrc',
    'canonicalize',
    'changelogithub',
    'chartjs',
    'chrono',
    'combak',
    'crosspost',
    'datelike',
    'dicebear',
    'docme',
    'docmeup',
    'docu',
    'docup',
    'docus',
    'docyou',
    'hexdigit',
    'humanwhocodes',
    'indicatif',
    'lightningcss',
    'mockall',
    'registerables',
    'replacen',
    'ropey',
    'serde',
    'singlefile',
    'todoctor',
    'todos',
    'trivias',
  ],
  ignorePaths: [
    '.github',
    'Cargo.lock',
    'changelog.md',
    'license',
    'pnpm-lock.yaml',
    'preview/elements/avatar.svelte',
    'preview/mock/data.ts',
    'tsconfig.json',
  ],
  dictionaries: ['css', 'html', 'node', 'npm', 'typescript'],
  useGitignore: true,
  language: 'en',
})
