allowBuilds:
  esbuild: true
  simple-git-hooks: true
  svelte-preprocess: true

configDependencies:
  '@pnpm/trusted-deps': 0.1.1+sha512-jI3PWNv2zCg9+KHI3qQTsa534c5nisZQrHFeWSyyHoUXcuzvjkXxQKPFLJ/qtNAF+PtKHDlRntO2aZKb3VDuHQ==

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@azat-io/*'

onlyBuiltDependenciesFile: node_modules/.pnpm-config/@pnpm/trusted-deps/allow.json

packages:
  - packages/**

