name: Install Tools

runs:
  using: composite
  steps:
    - name: Install Node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 24

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: rustfmt, clippy
        targets: |
          x86_64-unknown-linux-gnu
          aarch64-unknown-linux-gnu
          x86_64-apple-darwin
          aarch64-apple-darwin
          x86_64-pc-windows-msvc

    - name: Install pnpm
      uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      with:
        version: 11
        run_install: false
